# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('author', models.CharField(max_length=16, verbose_name='author')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create_time')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='category')),
                ('tags', models.CharField(blank=True, max_length=100, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='Cheapest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(blank=True)),
                ('reg_registrar', models.CharField(blank=True, max_length=30)),
                ('reg_price', models.FloatField(blank=True)),
                ('renew_registrar', models.CharField(blank=True, max_length=30)),
                ('renew_price', models.FloatField(blank=True)),
                ('tran_registrar', models.CharField(blank=True, max_length=30)),
                ('tran_price', models.FloatField(blank=True)),
                ('popularity', models.IntegerField(blank=True)),
                ('test', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='username')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('content', models.TextField(verbose_name='content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='update_time')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tld.Blog', verbose_name='blog')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatetime', models.DateTimeField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(max_length=30)),
                ('registry', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('cate', models.CharField(blank=True, max_length=30)),
                ('popular', models.IntegerField(blank=True)),
                ('restrictions', models.CharField(blank=True, max_length=200)),
                ('sources', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tld_domain',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.FloatField(blank=True)),
                ('renewal', models.FloatField(blank=True)),
                ('transfer', models.FloatField(blank=True)),
                ('whois', models.FloatField(blank=True)),
                ('test', models.TextField(blank=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tld.Domain')),
            ],
            options={
                'db_table': 'tld_price',
            },
        ),
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=50)),
                ('color', models.CharField(default='#fff', max_length=10)),
                ('review', models.TextField(blank=True)),
                ('rating', models.FloatField(blank=True)),
            ],
            options={
                'db_table': 'tld_registrar',
            },
        ),
        migrations.AddField(
            model_name='price',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tld.Registrar'),
        ),
    ]
