# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-24 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tld', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='domain',
            table='tlds_domain',
        ),
        migrations.AlterModelTable(
            name='price',
            table='tlds_price',
        ),
        migrations.AlterModelTable(
            name='registrar',
            table='tlds_registrar',
        ),
    ]
